### ISSUE TITLE
Refer to a String that can be set to a flag from a variable

### ISSUE THREAD

**Issue by crane-hiromu** [Matejkob/swift-spyable#84]
Thanks for the useful library :)

Now, I wrote `@Spyable(behindPreprocessorFlag: "DEBUG")` in a lot of code.
So I felt I would like to set "DEBUG" as a variable.

<img width="354" alt="Screenshot 2024-02-02 at 12 29 36" src="https://github.com/Matejkob/swift-spyable/assets/24838521/42687902-ccff-4ae5-ad15-d4fd7fcfe204">

In this case `if DEBUG` is not generated.
Are there any good way?

**Comment by Matejkob** [comment]
Hi @crane-hiromu,

thanks for your feedback! 🫶

Unfortunately, the argument requires a static string literal. We wouldn't have access to the content if you provided string dynamically or used interpolation. I have created a PR #85 that adds a diagnostic error if one would provide not static string literal.
