### ISSUE TITLE
Support `any`

### ISSUE THREAD

**Issue by crane-hiromu** [Matejkob/swift-spyable#90]
Thank you for creating this library 🤝

<br>

**Describe the bug**

Regarding `any`, which will definitely be implemented in swift in the future
-> https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md

<br>

We are unable to conduct tests because the code generated by Spyable macro lacks the 'any' attachment on the protocol.
If a new Xcode 15.3~ or flag is turned on...

<img width="1125" alt="Screenshot 2024-04-02 at 18 32 25" src="https://github.com/Matejkob/swift-spyable/assets/24838521/22f392fc-6aca-487f-b027-3f7bbe2cca54">

<br><br>

**To Reproduce**

When we use 

- `Xcode 15.3~`

or 

- `-enable-upcoming-feature ExistentialAny` flag

<br>

**Expected behavior**

Can run tests

<br>

**Additional context**

We are rewriting mock code using `Spyable` in a large-scale project. 
Your support with this task would be greatly appreciated in the nearly future.
Thanks 👍

**Comment by Matejkob** [comment]
Hey there!

I see what’s happening with the `any` keyword and Xcode 15.3+. I’m on it and will look into a fix asap.

Super grateful for your input.

Cheers,
Mateusz
